import type { Metadata } from "next";
import "./globals.css";
import { Rozha_One } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { EventProvider } from './context/EventContext';

const rozhaOne = Rozha_One({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-rozha-one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rozhaOne.className} flex flex-col min-h-screen`}>
        <EventProvider>
          <Header />
          <div className="flex-1">{children}</div>
          <Footer />
        </EventProvider>
      </body>
    </html>
  );
}
